modules/models/base.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import and_
from sqlalchemy.inspection import inspect
from math import ceil
from datetime import datetime

db = SQLAlchemy()

class BaseEntity(db.Model):
	__abstract__ = True

	fecha_alta = db.Column(db.DateTime, default=datetime.utcnow)
	fecha_modificacion = db.Column(db.DateTime, onupdate=datetime.utcnow)
	activo = db.Column(db.Boolean, default=True)

	def guardar(self):
		exito=True
		mensaje=""
		try:
			if self.id==None:
				db.session.add(self)
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			exito=False
			mensaje=str(e)
		return {"Resultado":self, "Exito":exito, "MensajePorFallo":mensaje}

	def borrar(self):
		exito=True
		mensaje=""
		try:
			db.session.delete(self)
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			exito=False
			mensaje=str(e)
		return {"Resultado":None, "Exito":exito, "MensajePorFallo":mensaje}

	def activar(self, estado):
		exito=True
		mensaje=""
		try:
			self.activo=estado
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			exito=False
			mensaje=str(e)
		return {"Resultado":None, "Exito":exito, "MensajePorFallo":mensaje}

	@classmethod
	def crear_y_obtener(cls, **kwargs):
		entidad = db.session.query(cls).filter_by(**kwargs).first()
		if not entidad:
			entidad = cls(**kwargs)
			db.session.add(entidad)
		return entidad
		
	def serialize(self):
		serializable_data = {}
		for column in self.__table__.columns:
			value = getattr(self, column.name)
			if isinstance(value, datetime):
				# Si el valor es de tipo datetime, aplicar isoformat()
				serializable_data[column.name] = value.isoformat()
			else:
				serializable_data[column.name] = value
		return serializable_data
	
	@staticmethod
	def obtener_paginado(query, pagina, items_por_pagina):
		total_objetos = query.count()
		total_paginas = ceil(total_objetos / items_por_pagina)
		objetos = query.paginate(page=pagina, per_page=items_por_pagina)
		return objetos, total_paginas
	
	@classmethod
	def obtener_todo(cls):
		objetos = cls.query.all()
		return objetos

modules/auth.py
import os
from flask import current_app, redirect, url_for, request, flash, render_template, abort, jsonify
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from modules.models.entities import User
from flask import Blueprint
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo
from flask_jwt_extended import create_access_token, jwt_required
from flask_wtf.csrf import CSRFProtect
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash

auth_bp = Blueprint('auth', __name__)

login_manager = LoginManager()
csrf = CSRFProtect()

class SignupForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=4, max=100)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=128)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@login_manager.unauthorized_handler
def unauthorized():
    if "/api/" in request.path:
        return abort(401)
    return redirect(url_for('auth.login'))


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('routes.index'))
    
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('routes.index'))
        else:
            flash("Credenciales no válidas. Intente nuevamente.", 'danger')
    return render_template('login.html', form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('routes.index'))

    form = SignupForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash("El nombre de usuario ya existe. Por favor, elige otro.", 'danger')
        else:
            new_user = User(username=username, password=password)
            new_user.set_password(password) 
            new_user.guardar()

            flash("Registro exitoso. Inicia sesión con tu nueva cuenta.", 'success')
            return redirect(url_for('auth.login'))
    
    return render_template('signup.html', form=form)


@auth_bp.route('/login-jwt', methods=['POST']) 
@csrf.exempt
def login_jwt():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    user = User.query.filter_by(username=username).first()
    if user and user.check_password(password):
        access_token = create_access_token(identity=username)
        return jsonify(access_token=access_token)
    else:
        return jsonify({"msg":"Credenciales inválidas"}),401

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

def jwt_or_login_required():
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            try:
                jwt_required()(lambda: None)()
            except:
                if current_user.is_authenticated:
                    return f(*args, **kwargs)
                return {"message": "Acceso no autorizado"}, 401
            return f(*args, **kwargs)

        return decorated_function
    return decorator

modules/routes.py
from flask import Blueprint, render_template, redirect, url_for, session,flash
from flask_login import login_required, logout_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, IntegerField
from wtforms.validators import DataRequired, Email, Length, NumberRange
from modules.common.gestor_email import gestor_email 

from flask import Blueprint

routes_bp = Blueprint('routes', __name__)

# Definir el formulario de contacto
class ContactForm(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired()])
    email = StringField('Correo Electrónico', validators=[DataRequired()])
    message = StringField('Mensaje', validators=[DataRequired()])
    submit = SubmitField('Enviar')

# Manejar rutas no válidas
@routes_bp.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@routes_bp.route('/')
def home():
    return redirect(url_for('auth.login'))

@routes_bp.route('/index')
@login_required
def index():
    return render_template('index.html')

@routes_bp.route('/about')
def about():
    return render_template('about.html')

@routes_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        email = form.email.data
        nombre = form.name.data
        mensaje_enviado = form.message.data

        mensaje_respuesta= f'Hola {nombre}\n Recibimos tu mensaje por medio de la web de EduGestión. Gracias por contactarnos.\n\nSu mensaje:\n{mensaje_enviado}'
        resultado=gestor_email().enviar_email(email,"Formulario de contacto",mensaje_respuesta)
        if resultado["Exito"]:
            flash('Formulario enviado con éxito', 'success')
            return redirect(url_for('routes.index'))
        else:
            flash(resultado["MensajePorFallo"], 'warning')
    return render_template('contact.html', form=form)

templates/comun/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduGestion</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="./static/img/libro.svg">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque&family=Poppins:wght@300&family=Questrial&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
       <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.4.1/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.3.2/css/fixedHeader.bootstrap.min.css">
  

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Bricolage+Grotesque&family=Poppins:wght@300&family=Questrial&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/responsive.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.3.2/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>
  <body>
        <div class="flash-message" style="background-color:#ADAFB2 ; margin: 0px;">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert fondo" style="height: 8vh; background-color:#ADAFB2 ; margin: 0px;">
            {{ messages[] }}
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <nav class="navbar navbar-expand-lg menu">
        <div class="container-fluid">
        <a class="navbar-brand d-flex logo" style="color: black; gap: 3px;" href="{{ url_for('routes.index') }}"><img src="../static/img/libro.svg" alt="logo" style="width: 25px;"><span>EduGestión</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon d-flex"><i class="fas fa-bars"></i></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav d-flex">
              <li class="nav-item ">
                  <a class="nav-link links" href="{{ url_for('routes.index') }}">INICIO</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link links" href="{{ url_for('routes.about') }}">ACERCA DE</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link links" href="{{ url_for('routes.contact') }}">CONTACTO</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link btn btn-danger" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link btn btn-primary" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>
    <div class="">
          {% for message in get_flashed_messages() %}
          <div class="alert alert-warning" style="margin: 0px;">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ message }}
          </div>
          {% endfor %}
          {% block content %}
          {% endblock %}
    </div>
    <footer>
          {% block footer %}
            {% include 'footer.html' %}
          {% endblock %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

templates/comun/genero.html
{% macro campo_genero(selected_genero) %}
<label for="genero" class="form-label">Género</label>
<select class="form-control" id="genero" name="genero">
	<option value="" disabled selected>Seleccionar Género</option>
	<!-- Opciones cargadas desde la API -->
</select>

<script>
	document.addEventListener('DOMContentLoaded', function () {
		const generoSelect = document.getElementById("genero");
		const seleccionAnterior = "{{ selected_genero }}"; // Valor enviado desde la macro

		// Cargar opciones desde la API
		fetch('/api/generos')
			.then(response => response.json())
			.then(data => {
				if (data.Exito) {
					const generos = data.Resultado;
					generos.forEach(genero => {
						const option = document.createElement("option");
						option.value = genero.nombre;
						option.textContent = genero.nombre;
						generoSelect.appendChild(option);
					});

					// Seleccionar el género enviado
					generoSelect.value = seleccionAnterior;
					
					const otraOpcion = document.createElement("option");
					otraOpcion.value = "Otro";
					otraOpcion.textContent = "Otro";
					generoSelect.appendChild(otraOpcion);
				}
			})
			.catch(error => console.error("Error al cargar los géneros:", error));

		$('#genero').change(function() {
			if ($(this).val() === 'Otro') {
				const nuevoGenero = prompt("Ingrese nuevo género:");
				if (nuevoGenero) {
					const nuevaOpcion = document.createElement("option");
					nuevaOpcion.value = nuevoGenero;
					nuevaOpcion.textContent = nuevoGenero;
					generoSelect.insertBefore(nuevaOpcion, generoSelect.lastElementChild);
					generoSelect.value = nuevoGenero;
				} else {
					// Restaurar la selección anterior
					generoSelect.value = seleccionAnterior;
				}
			}
		});
	});
</script>
{% endmacro %}

templates/comun/lugares.html
{% macro campos_lugares(selected_pais,selected_provincia,selected_ciudad,selected_barrio) %}
<div class="col mb-3">
	<label for="pais" class="form-label">País</label>
	<select class="form-control" id="pais" name="pais">
		<option value="" disabled selected>Seleccionar País</option>
	</select>
</div>
<div class="col mb-3">
	<label for="provincia" class="form-label">Provincia</label>
	<select class="form-control" id="provincia" name="provincia" disabled>
		<option value="" disabled selected>Seleccionar Provincia</option>
	</select>
</div>
<div class="col mb-3">
	<label for="ciudad" class="form-label">Ciudad</label>
	<select class="form-control" id="ciudad" name="ciudad" disabled>
		<option value="" disabled selected>Seleccionar Ciudad</option>
	</select>
</div>
<div class="col mb-3">
	<label for="barrio" class="form-label">Barrio</label>
	<select class="form-control" id="barrio" name="barrio" disabled>
		<option value="" disabled selected>Seleccionar Barrio</option>
	</select>
</div>
<script>
	document.addEventListener('DOMContentLoaded', function () {
		const paisSelect = document.getElementById("pais");
		const provinciaSelect = document.getElementById("provincia");
		const ciudadSelect = document.getElementById("ciudad");
		const barrioSelect = document.getElementById("barrio");
		const seleccionPaisAnterior = "{{ selected_pais }}"; // Valor enviado desde la macro
		const seleccionProvinciaAnterior = "{{ selected_provincia }}"; // Valor enviado desde la macro
		const seleccionCiudadAnterior = "{{ selected_ciudad }}"; // Valor enviado desde la macro
		const seleccionBarrioAnterior = "{{ selected_barrio }}"; // Valor enviado desde la macro

		// Cargar opciones de País desde la API
		fetch('/api/lugares/obtener_paises')
			.then(response => response.json())
			.then(data => {
				if (data.Exito) {
					const paises = data.Resultado;
					paises.forEach(pais => {
						const option = document.createElement("option");
						option.value = pais.nombre;
						option.textContent = pais.nombre;
						paisSelect.appendChild(option);
						if (pais.nombre===seleccionPaisAnterior){paisSelect.value = seleccionPaisAnterior;}
					});
					const otraOpcion = document.createElement("option");
					otraOpcion.value = "Otro";
					otraOpcion.textContent = "Otro";
					paisSelect.appendChild(otraOpcion);

					// Disparar manualmente el evento change del país
					const changeEvent = new Event('change');
					paisSelect.dispatchEvent(changeEvent);
				}
			})
			.catch(error => console.error("Error al cargar los países:", error));

		// Evento de cambio para País
		paisSelect.addEventListener('change', function () {
			const selectedPais = this.value;

			// Resetear las opciones anteriores
			provinciaSelect.innerHTML = '<option value="" disabled selected>Seleccionar Provincia</option>';
			ciudadSelect.innerHTML = '<option value="" disabled selected>Seleccionar Ciudad</option>';
			barrioSelect.innerHTML = '<option value="" disabled selected>Seleccionar Barrio</option>';
			provinciaSelect.disabled = true;
			ciudadSelect.disabled = true;
			barrioSelect.disabled = true;

			// Cargar opciones de Provincia desde la API
			if (selectedPais) {
				fetch('/api/lugares/obtener_provincias', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json'
					},
					body: JSON.stringify({ pais: selectedPais })
				})
					.then(response => response.json())
					.then(data => {
						if (data.Exito) {
							const provincias = data.Resultado;
							provincias.forEach(provincia => {
								const option = document.createElement("option");
								option.value = provincia.nombre;
								option.textContent = provincia.nombre;
								provinciaSelect.appendChild(option);
								if (provincia.nombre===seleccionProvinciaAnterior){provinciaSelect.value = seleccionProvinciaAnterior;}
							});
							provinciaSelect.disabled = false;
							const otraOpcion = document.createElement("option");
							otraOpcion.value = "Otro";
							otraOpcion.textContent = "Otro";
							provinciaSelect.appendChild(otraOpcion);
							// Disparar manualmente el evento change de provincia
							const changeEvent = new Event('change');
							provinciaSelect.dispatchEvent(changeEvent);

						}
					})
					.catch(error => console.error("Error al cargar las provincias:", error));
			}
		});

		// Evento de cambio para Provincia
		provinciaSelect.addEventListener('change', function () {
			const selectedPais = paisSelect.value;
			const selectedProvincia = this.value;

			// Resetear las opciones anteriores
			ciudadSelect.innerHTML = '<option value="" disabled selected>Seleccionar Ciudad</option>';
			barrioSelect.innerHTML = '<option value="" disabled selected>Seleccionar Barrio</option>';
			ciudadSelect.disabled = true;
			barrioSelect.disabled = true;

			// Cargar opciones de Ciudad desde la API
			if (selectedPais && selectedProvincia) {
				fetch('/api/lugares/obtener_ciudades', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json'
					},
					body: JSON.stringify({ pais: selectedPais, provincia: selectedProvincia })
				})
					.then(response => response.json())
					.then(data => {
						if (data.Exito) {
							const ciudades = data.Resultado;
							ciudades.forEach(ciudad => {
								const option = document.createElement("option");
								option.value = ciudad.nombre;
								option.textContent = ciudad.nombre;
								ciudadSelect.appendChild(option);
								if (ciudad.nombre===seleccionCiudadAnterior){ciudadSelect.value = seleccionCiudadAnterior;}
							});
							ciudadSelect.disabled = false;
							const otraOpcion = document.createElement("option");
							otraOpcion.value = "Otro";
							otraOpcion.textContent = "Otro";
							ciudadSelect.appendChild(otraOpcion);
							// Disparar manualmente el evento change de ciudad
							const changeEvent = new Event('change');
							ciudadSelect.dispatchEvent(changeEvent);
						}
					})
					.catch(error => console.error("Error al cargar las ciudades:", error));
			}
		});

		// Evento de cambio para Ciudad
		ciudadSelect.addEventListener('change', function () {
			const selectedPais = paisSelect.value;
			const selectedProvincia = provinciaSelect.value;
			const selectedCiudad = this.value;

			// Resetear las opciones anteriores
			barrioSelect.innerHTML = '<option value="" disabled selected>Seleccionar Barrio</option>';
			barrioSelect.disabled = true;

			// Cargar opciones de Barrio desde la API
			if (selectedPais && selectedProvincia && selectedCiudad) {
				fetch('/api/lugares/obtener_barrios', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json'
					},
					body: JSON.stringify({ pais: selectedPais, provincia: selectedProvincia, ciudad: selectedCiudad })
				})
					.then(response => response.json())
					.then(data => {
						if (data.Exito) {
							const barrios = data.Resultado;
							barrios.forEach(barrio => {
								const option = document.createElement("option");
								option.value = barrio.nombre;
								option.textContent = barrio.nombre;
								barrioSelect.appendChild(option);
								if (barrio.nombre===seleccionBarrioAnterior){barrioSelect.value = seleccionBarrioAnterior;}
							});
							barrioSelect.disabled = false;
							const otraOpcion = document.createElement("option");
							otraOpcion.value = "Otro";
							otraOpcion.textContent = "Otro";
							barrioSelect.appendChild(otraOpcion);
							// Disparar manualmente el evento change de barrio
							const changeEvent = new Event('change');
							barrioSelect.dispatchEvent(changeEvent);
						}
					})
					.catch(error => console.error("Error al cargar los barrios:", error));
			}
		});

		// Agregar opción "Otro" y manejar entrada de nuevos elementos
		const selects = [paisSelect, provinciaSelect, ciudadSelect, barrioSelect];
		selects.forEach(select => {
			select.addEventListener('change', function () {
				if (select.value === 'Otro') {
					const nuevoElemento = prompt(`Ingrese nuevo valor para ${select.id}`);
					if (nuevoElemento) {
						const nuevaOpcion = document.createElement("option");
						nuevaOpcion.value = nuevoElemento;
						nuevaOpcion.textContent = nuevoElemento;
						select.insertBefore(nuevaOpcion, select.lastElementChild);
						select.value = nuevoElemento;
					} else {
						// Restaurar la selección anterior
						select.value = select.id === 'pais' ? seleccionPaisAnterior :
							select.id === 'provincia' ? seleccionProvinciaAnterior :
								select.id === 'ciudad' ? seleccionCiudadAnterior :
									select.id === 'barrio' ? seleccionBarrioAnterior :
										"";
					}
				}
			});
		});
	});
</script>
{% endmacro %}

templates/comun/modal_eliminar.html
{% macro confirmar_eliminar(id, delete_route, confirm_message) %}
<div class="modal fade" id="eliminarModal{{ id }}" tabindex="-1" role="dialog" aria-labelledby="eliminarModalLabel{{ id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="eliminarModalLabel{{ id }}">Confirmar Eliminación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ confirm_message }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form action="{{ delete_route }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

templates/comun/paginado.html
{% macro render_paginado(endpoint, items, filtros=None) %}
<nav aria-label="Paginación">
    <ul class="pagination">
        {% if items.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=1, **(filtros or {})) }}">Primera</a>
        </li>
        {% endif %}

        {% for num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if num %}
        <li class="page-item {% if num == items.page %}active{% endif %}">
            <a class="page-link" href="{{ url_for(endpoint, page=num, **(filtros or {})) }}">{{ num }}</a>
        </li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">...</span></li>
        {% endif %}
        {% endfor %}

        {% if items.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=items.pages, **(filtros or {})) }}">Última</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}